### ISSUE TITLE
Overview tasks

### ISSUE THREAD

**Issue by lauraluiz** [commercetools/sphere-donut#17]
- [ ] https://github.com/commercetools/sphere-donut/issues/9 Use latest release of SPHERE.IO JVM SDK
- [ ] https://github.com/commercetools/sphere-donut/issues/8 Update Play to latest 2.3.x
- [ ] https://github.com/commercetools/sphere-donut/issues/10 Rewrite the code Java 8 style
- [ ] https://github.com/commercetools/sphere-donut/issues/11 Never again kill a Promise
- [ ] https://github.com/commercetools/sphere-donut/issues/16 Use dependency injection library
- [ ] https://github.com/commercetools/sphere-donut/issues/13 Make it configurable
- [ ] https://github.com/commercetools/sphere-donut/issues/14 Override configuration with environment variables
- [ ] https://github.com/commercetools/sphere-donut/issues/12 Update README.md
